# Generated by Django 3.0.4 on 2021-04-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
